### ISSUE TITLE
Revisión de README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto-pacman#1]
Hola,

- Aún no habéis cumplimentado la plantilla con vuestra propuesta.
- El equipo debe tener al menos 3 integrantes.
- El juego del trivial ya se ha realizado en cursos anteriores, y hay [otra propuesta para este curso](https://github.com/aigora/twIE_2021-ingenieritas-0-2). Debéis esforzaros por ser originales y diferenciaros de lo que ya se ha hecho.

**Comment by Alejandroillera** [comment]
Ya hemos decidido el trabajo, pero no sabemos si sería posible cambiar el nombre del grupo de trabajo. Hemos decidido hacer un Pacma y para no haber confusiones, nos gustaría cambiar el nombre de proyecto trivial a proyecto pacma

**Comment by oscarperpinan** [comment]
Hecho. He cambiado tanto el nombre del repositorio como el nombre del equipo.

**Comment by oscarperpinan** [comment]
He comprobado el README y está todo correcto. Adelante.
