### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-pacman#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by oscarperpinan** [comment]
Para que el código sea portable (es decir, para que pueda compilarse y ejecutarse en cualquier sistema operativo), debéis emplear únicamente librerías estándar. En particular, debéis evitar las librerías windows.h y conio.h. Modificad el código del menú para eliminarlas.

**Comment by Alopez-hermida** [comment]
Ya he modificado el menú, eliminado las dos librerías (windows.h y conio.h) y eliminado el código relacionado con ellas
